# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
