# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 11:20
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20180830_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='to do', max_length=100, no_check_for_status=True),
        ),
    ]
