# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 11:23
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
    ]
