# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:44
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20180907_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugform',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='feature_status'),
        ),
        migrations.AlterField(
            model_name='featureticketform',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='feature_status'),
        ),
    ]
