# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:48
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20180907_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugform',
            name='feature_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='feature', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='featureticketform',
            name='feature_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='feature', max_length=100, no_check_for_status=True),
        ),
        migrations.AlterField(
            model_name='featureticketform',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status'),
        ),
    ]
