# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 13:50
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20180907_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureticketform',
            old_name='feature_status',
            new_name='issue_status',
        ),
        migrations.RemoveField(
            model_name='bugform',
            name='feature_status',
        ),
        migrations.AddField(
            model_name='bugform',
            name='issue_status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='bug', max_length=100, no_check_for_status=True),
        ),
    ]
