# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0013_auto_20180907_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('status', model_utils.fields.StatusField(choices=[('to do', 'to do'), ('doing', 'doing'), ('done', 'done')], default='to do', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('issue_status', model_utils.fields.StatusField(choices=[('bug', 'bug'), ('feature', 'feature')], default='bug', max_length=100, no_check_for_status=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('status', model_utils.fields.StatusField(choices=[('to do', 'to do'), ('doing', 'doing'), ('done', 'done')], default='to do', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status')),
                ('issue_status', model_utils.fields.StatusField(choices=[('feature', 'feature'), ('bug', 'bug')], default='feature', max_length=100, no_check_for_status=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bugform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='featureticketform',
            name='author',
        ),
        migrations.DeleteModel(
            name='BugForm',
        ),
        migrations.DeleteModel(
            name='FeatureTicketForm',
        ),
    ]
