# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0014_auto_20180907_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugticket',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='bug_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureticket',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='feature_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
