# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_auto_20180909_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugticket',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
