# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0017_auto_20180911_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', model_utils.fields.StatusField(choices=[('to do', 'to do'), ('doing', 'doing'), ('done', 'done')], default='to do', max_length=100, no_check_for_status=True)),
                ('issue_status', model_utils.fields.StatusField(choices=[('bug', 'bug'), ('feature', 'feature')], default='bug', max_length=100, no_check_for_status=True)),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='issue_status')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='bug_upvotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bugticket',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bugticket',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='BugTicket',
        ),
    ]
