# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_auto_20180915_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='published_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
