# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_auto_20180915_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='published_date',
            new_name='updated_date',
        ),
    ]
