# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_auto_20180915_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
